### ISSUE TITLE
`panic: runtime error: index out of range [129] with length 129`

### ISSUE THREAD

**Issue by soredake** [MrMarble/yoink#5]
```
❯ yoink --config /mnt/gdrive_mount/documents/oracle/yoink.yaml

██╗   ██╗ ██████╗ ██╗███╗   ██╗██╗  ██╗
╚██╗ ██╔╝██╔═══██╗██║████╗  ██║██║ ██╔╝
 ╚████╔╝ ██║   ██║██║██╔██╗ ██║█████╔╝
  ╚██╔╝  ██║   ██║██║██║╚██╗██║██╔═██╗
   ██║   ╚██████╔╝██║██║ ╚████║██║  ██╗
   ╚═╝    ╚═════╝ ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝
           0.5.0 - MrMarble

Total download size: 50GB
Checking qbt connection... OK
Found 13 torrents in qBittorrent:
  [1.9 GB] Systems Design Fundamentals Algo++
  [219 kB] Friends with Benefits Goals by Barbi Cox.epub
  [237 kB] John C. Maxwell - How Successful People Think.epub
  [1.0 GB] The Complete ChatGPT Guide From Zero to Hero 2023
  [8.2 GB] Assembly
  [16 GB] [GeeksForGeeks] Data Structures With Python
  [319 MB] The Art And Science Of Modern Hacking
  [16 GB] CBT Nuggets - Cisco Certification Training 200-301...
  [43 MB] Mastering Vim Quickly - The Premium Training...
  [187 kB] Daddy's Little Djinn by Joe Satoria.epub
  [257 kB] The Loneliness Companion_ A Pra - Shrein H....
  [225 kB] Brook Wilder - 5 Sinful Haven (Rough Jesters MC...
  [228 kB] Brook Wilder - 4 Ruined Mercy (Rough Jesters MC...
Used space: 43 GB, Left: 6.8 GB
Checking prowlarr connection... OK
Searching for freeleech torrents...
Found 186 freeleech torrents:
panic: runtime error: index out of range [129] with length 129

goroutine 1 [running]:
main.(*RunCmd).Run(0x1?, 0x400009fc40)
        github.com/mrmarble/yoink/cmd/yoink/run.go:78 +0x1564
reflect.Value.call({0x3a0720?, 0x40000a17b1?, 0x400010db28?}, {0x405ec6, 0x4}, {0x40000a8738, 0x1, 0x2a0c54?})
        reflect/value.go:586 +0x838
reflect.Value.Call({0x3a0720?, 0x40000a17b1?, 0x3af920?}, {0x40000a8738?, 0x403d40?, 0x70e660?})
        reflect/value.go:370 +0x90
github.com/alecthomas/kong.callMethod({0x405cbd, 0x3}, {0x3a9a60?, 0x40000a17b1?, 0x3?}, {0x3a0720?, 0x40000a17b1?, 0x82f74?}, 0x42000040000ad210?)
        github.com/alecthomas/kong@v0.7.1/callbacks.go:95 +0x3cc
github.com/alecthomas/kong.(*Context).RunNode(0x40000ee600, 0x40000fc2d0, {0x400010df28, 0x1, 0x1})
        github.com/alecthomas/kong@v0.7.1/context.go:755 +0x468
github.com/alecthomas/kong.(*Context).Run(0x40000a17a0?, {0x400010df28?, 0x400010df38?, 0x40000023c8?})
        github.com/alecthomas/kong@v0.7.1/context.go:780 +0x144
main.main()
        github.com/mrmarble/yoink/cmd/yoink/main.go:63 +0x208
```

My config:
```
total_freeleech_size: "50GB" # Max space to use for downloads. If 0, no limit is applied
category: "FreeLeech" # Category to use for downloads.
paused: false # Whether to pause torrents after adding them to qBittorrentf
qbittorrent: # Connection details for qBittorrent
  host: "http://localhost:22222/"
  username: ""
  password: ""
prowlarr: # Connection details for Prowlarr
  host: "http://localhost:9666/"
  api_key: ""
indexers: # List of indexers to use. Filters out any indexers not in this list
  - id: 27 # ID of the indexer in Prowlarr
    max_seeders: 20 # Maximum number of seeders to allow. 0 = no limit
    max_size: "25GB" # Maximum file size to allow. 0 = no limit
    min_leechers: 0 # Minimum number of leechers to allow. 0 = no limit
  - id: 36 # ID of the indexer in Prowlarr
    max_seeders: 20 # Maximum number of seeders to allow. 0 = no limit
    max_size: "25GB" # Maximum file size to allow. 0 = no limit
    min_leechers: 0 # Minimum number of leechers to allow. 0 = no limit
  - id: 39 # ID of the indexer in Prowlarr
    max_seeders: 20 # Maximum number of seeders to allow. 0 = no limit
    max_size: "25GB" # Maximum file size to allow. 0 = no limit
    min_leechers: 0 # Minimum number of leechers to allow. 0 = no limit
```

**Comment by ramgoat** [comment]
Encountered the same issue.  Shame - yoink was _exactly_ what I'm looking for.

```
Total download size: 200
Checking qbt connection... OK
Found 0 torrents in qBittorrent:
Used space: 0 B, Left: 200 B
Checking prowlarr connection... OK
Searching for freeleech torrents...
Found 93 freeleech torrents:
panic: runtime error: index out of range [47] with length 46
goroutine 1 [running]:
main.(*RunCmd).Run(0x1?, 0xc00009f910)
	github.com/mrmarble/yoink/cmd/yoink/run.go:78 +0x1c54
reflect.Value.call({0x7f5920?, 0xc0000a17b1?, 0x44c856?}, {0x85b1b2, 0x4}, {0xc0000a87e0, 0x1, 0x1?})
	reflect/value.go:586 +0xb07
reflect.Value.Call({0x7f5920?, 0xc0000a17b1?, 0x804b20?}, {0xc0000a87e0?, 0x859020?, 0xb6b6c0?})
	reflect/value.go:370 +0xbc
github.com/alecthomas/kong.callMethod({0x85af9d, 0x3}, {0x7fec60?, 0xc0000a17b1?, 0x3?}, {0x7f5920?, 0xc0000a17b1?, 0xc000111d08?}, 0x4773f8?)
	github.com/alecthomas/kong@v0.7.1/callbacks.go:95 +0x4fa
github.com/alecthomas/kong.(*Context).RunNode(0xc0000f0600, 0xc0000fe2d0, {0xc000111f30, 0x1, 0x1})
	github.com/alecthomas/kong@v0.7.1/context.go:755 +0x60f
github.com/alecthomas/kong.(*Context).Run(0xc0000a17a0?, {0xc000111f30?, 0xc000111f40?, 0xc000062058?})
	github.com/alecthomas/kong@v0.7.1/context.go:780 +0x14e
main.main()
	github.com/mrmarble/yoink/cmd/yoink/main.go:63 +0x233
```
